export const DOMelements = {
    settingsImage: document.querySelector(".settings__image"),
    temp: document.querySelector('.info__item--temperature--js'),
    humidity: document.querySelector('.info__item--humidity--js'),
    clouds: document.querySelector('.info__item--clouds--js'),
    wind: document.querySelector('.info__item--wind--js'),
    sunrise: document.querySelector('.info__item--sunrise--js'),
    sunset: document.querySelector('.info__item--sunset--js'),
    searchButton: document.querySelector(".searchButton"),
    currentlocation: document.querySelector('.current__location'),
    cities: document.querySelector('.cities'),
    settingsList: document.querySelector('.settings__list'),
    cities__toEditList: document.querySelector('.cities__toEditList'),
    hamburger: document.querySelector('.hamburger--js'),
    settings: document.querySelector('.settings--js'),
    settingsEdit: document.querySelector('.settings--js'),
    about: document.querySelector(".settings__item--about"),
    editCitiesList: document.querySelector(".settings__item--edit"),
    listCitiesToEdit: document.querySelector(".cities__toEditList"),
    modal: document.getElementById("myModal"),
    today: document.querySelector(".current__days--today"),
    tomorrow: document.querySelector(".current__days--tomorrow"),
    time: document.querySelector('.current__time'),
    date: document.querySelector('.current__date'),
    day: document.querySelector('.current__day'),
    url: "https://api.weatherapi.com/v1/forecast.json?key:3f1ad206d1b94436825173623201101&q:",
    // main: document.querySelector(".main"),
    searchInputButton: document.querySelector(".cities__item--input"),
    // searchInput: document.querySelector(".searchModal--input"),
    matchList: document.querySelector('.matchList'),
    update: document.querySelector('.update__last'),
    searchModal: document.querySelector('.searchModal'),
    // listener : SwipeListener(main)

}